### ISSUE TITLE
State wrapper crashes when opening Preferences dialog

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/calculus-grapher#308] opened 2023-03-22 22:36 UTC
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/921.
In the state wrapper, if you open the preferences menu in the top sim and state is set twice while it is open, the bottom sim freezes and does not update even if state is set again.
**Visuals**
<img width="446" alt="pmenu" src="https://user-images.githubusercontent.com/41024075/227052246-e0b20f8a-c006-4b74-bee2-ab0512feec54.png">
<img width="444" alt="pmenu2" src="https://user-images.githubusercontent.com/41024075/227052257-cd25a27e-4eb8-4acb-bc34-a44d51ed20a5.png">

**Comment by pixelzoom** [comment] 2023-03-23 12:28
I have not investigated yet. But there's nothing sim-specific that is done here, other than creating UI controls for the Simulation tab.  So I suspect that this is a common-code problem, and likely occurs in other sims.

**Comment by veillette** [comment] 2023-03-23 12:49
I was able to reproduce with https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25/phet-io/wrappers/state/ but i checked master to reproduce and it does not show this problem. Master is laggy but you never see an empty preference menu like above.

**Comment by pixelzoom** [comment] 2023-03-23 12:58
Steps to reproduce:
1. Go the the wrapper index.
2. Choose "State" to launch the State Wrapper
3. Press the Preferences button in the navigation bar to open the Preferences dialog.

The downstread sim's Preference dialog is empty, except for the "Preferences" title. There is no output in the console, and the downstream sim becomes totally unresponsive. 

I reproduced this in the QA dev-test version (published 3/20/2023 03:37:25 UTC):
https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25/phet-io

I cannot reproduce in master, or in a fresh dev version published off of master (published 3/23/2023 12:49:26 UTC):
 https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.26/phet-io

Since there have been no related changes to the sim, something must have changed in common code. @zepumph @samreid is the PhET-iO team aware of any changes that might account for this?  Also asking @jessegreenberg, since it looks like he's been active in joist/js/preferences/.

**Comment by samreid** [comment] 2023-03-23 13:25
I confirmed the reported behavior. Empty dialog in dev.25 but working fine in dev.26. I'm not sure what would explain that problem.  If asked to investigate further, I would probably clone dev.25 based on its shas in a fresh checkout, adjacent to dev.26 (in a fresh checkout), then compare the diffs.  Self-unassigning for now.

**Comment by jessegreenberg** [comment] 2023-03-23 14:09
Sorry, Im not sure what would cause this. Changes Ive made in joist are minor and after 3/20/23. I did try the wrapper though. Downstream sim is responsive but state is never set. I see a warning every time it tries to set state:
![image](https://user-images.githubusercontent.com/6396244/227229015-dc34177d-2971-4712-83c8-4911cd821929.png)

**Comment by pixelzoom** [comment] 2023-03-23 15:11
@jessegreenberg can you please clarify? In which version of the sim is "Downstream sim is responsive but state is never set."  In master and 1.0.0-dev.26, the downstream sim mirrors changes that I make in the upstream sim.

I also see the error "attempt was made to remove a sound generator from an uninitialized sound manager, ignoring".  And the number of errors continues to update when I'm not interacting with the sim.

**Comment by jessegreenberg** [comment] 2023-03-23 15:23
I was testing dev.25 (https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25/phet-io/wrappers/state/).

**Comment by pixelzoom** [comment] 2023-03-23 15:33
> I should clarify, I see the downstream sim is responsive to user input. But it stops receiving state from the upstream sim the second time state is set while the Preferences dialog is open.

Sorry to keep bugging you.  But I have no idea what you mean by "the second time state is set", so I can't reproduce. Can you please provide explicity steps to reproduce?

**Comment by jessegreenberg** [comment] 2023-03-23 15:48
Just noting it seems to break after the second time state is set with Preferences open. To reproduce:
- Go to https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25/phet-io/wrappers/state/
- Slide the "Set State Rate" slider to 0.
- Open Preferences dialog in the upstream sim.
- Press "Set State Now" -----> Preferences dialog in downstream sim looks good.
- Press "Set State Now" again ------ Preferences dialog clears for some reason, further attempts to set state do nothing.

**Comment by pixelzoom** [comment] 2023-03-23 15:55
Thanks @jessegreenberg, that's very helpful.  I can reproduce using those steps in 1.0.0-dev.25.  I cannot reproduce in master or 1.0.0-dev.26.  So it looks like it's fixed in master.  But it's disconcerting that no one seems to know why it's fixed, or what was fixed.

**Comment by pixelzoom** [comment] 2023-03-23 15:59
Removing blocks-sim-publication label, since it's no longer broken in master.  But it would still be nice to know what changed, since we're in the middle of a dev test, and will be picking up unknown changes when we create the release branch.

**Comment by zepumph** [comment] 2023-03-23 16:46
After adding `?phetioDebug=true` in dev.25 here is the error, you have to "pause on caught exceptions" to get in the stack trace.

```
TypeError: Cannot read properties of null (reading 'minimumWidth')
    at ut.layout (calculus-grapher_all_phet-io_debug.html?ea&postMessageOnError&phetioDebug=true&frameTitle=destination:1231:1444436)
    at ut.updateLayout (calculus-grapher_all_phet-io_debug.html?ea&postMessageOnError&phetioDebug=true&frameTitle=destination:1231:980672)
    at ut.updateLayoutAutomatically (calculus-grapher_all_phet-io_debug.html?ea&postMessageOnError&phetioDebug=true&frameTitle=destination:1231:980781)
    at r.emit (calculus-grapher_all_phet-io_debug.html?ea&postMessageOnError&phetioDebug=true&frameTitle=destination:1231:29545)
    at r.notifyListeners (calculus-grapher_all_phet-io_debug.html?ea&postMessageOnError&phetioDebug=true&frameTitle=destination:1231:32020)
    at r.set (calculus-grapher_all_phet-io_debug.html?ea&postMessageOnError&phetioDebug=true&frameTitle=destination:1231:31562)
    at set value [as value] (calculus-grapher_all_phet-io_debug.html?ea&postMessageOnError&phetioDebug=true&frameTitle=destination:1231:31473)
    at ct._updateLocalPreferredWidth (calculus-grapher_all_phet-io_debug.html?ea&postMessageOnError&phetioDebug=true&frameTitle=destination:1231:590786)
    at r.emit (calculus-grapher_all_phet-io_debug.html?ea&postMessageOnError&phetioDebug=true&frameTitle=destination:1231:29545)
    at r.notifyListeners (calculus-grapher_all_phet-io_debug.html?ea&postMessageOnError&phetioDebug=true&frameTitle=destination:1231:32020)
```

**Comment by pixelzoom** [comment] 2023-03-23 22:15
Thanks, but that stack trace tells me almost nothing, because everything is mangled.  

Rather than spend more time on this, I posted to Slack#dev-public:
>In our dev test for Calculus Grapher, QA reported that the Preferences dialog was crashing in the PhET-iO State Wrapper. See https://github.com/phetsims/calculus-grapher/issues/308.  That’s no longer happening in master, but it’s disconcerting that no one involved (so far) recalls fixing anything.  Does this sound familiar to anyone? If so, please comment in the issue. If not, I’m going to close the issue, and :crossed_fingers: that master will be in good shape when we create the release branch.

**Comment by pixelzoom** [comment] 2023-03-24 13:15
One clue in the stack trace is the presence of `updateLayoutAutomatically`.  That's a method in LayoutConstraints.ts, so I suspect that some layout problem may have been corrected.  But I don't see any recent changes to LayoutConstraints, FlowBox, GridBox, etc.

**Comment by pixelzoom** [comment] 2023-03-24 15:20
My question in Slack#dev-public did not result in an answer.  Closing.

**Closed by pixelzoom** 2023-03-24 15:20 UTC
Labels: type:bug, dev:phet-io
