### ISSUE TITLE
Credits for 1.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#202] opened 2023-01-28 08:32 UTC
All credits except QA can be filled in at any time.

QA credits should be filled in during the QA process, after each dev-test and RC-test cycle.

**Comment by amanda-phet** [comment] 2023-01-31 18:09
Lead Designer: Amanda McGarry
Team: Catherine Carter, Michael Dubson, Brandon Li, Ariel Paul, Kathy Perkins,

**Comment by pixelzoom** [comment] 2023-01-31 20:31
I added https://github.com/phetsims/calculus-grapher/issues/202#issuecomment-1410848535 to the credits. I also took an initial stab at "softwareDevelopment", see below. @veillette does this seem correct to you?

<img width="511" alt="screenshot_2220" src="https://user-images.githubusercontent.com/3046552/215875799-f36e99f7-9eee-40f7-88ba-2c18df8c9428.png">

**Comment by amanda-phet** [comment] 2023-01-31 20:40
If Brandon is listed in development I don't think he needs to be in team. I
wasn't sure how we are handling large development teams so I put him in
team, but please go ahead and delete him from team.

**Comment by pixelzoom** [comment] 2023-01-31 20:55
Thanks for noticing that @amanda-phet. I confirmed with @veillette: Brandon made a significant contribution to the early software development, so it's appropriate that he is listed in Software Development. So I've removed him from Team in the above commit.

**Comment by veillette** [comment] 2023-02-08 14:32
Yes, that looks correct to me for the software development team.

**Comment by veillette** [comment] 2023-02-08 14:33
Unassigning until we circle back to it for the QA credits.

**Comment by pixelzoom** [comment] 2023-03-22 14:19
In the above commit, I added @Nancy-Salpepi and @KatieWoe for their role in https://github.com/phetsims/qa/issues/921.

**Comment by Nancy-Salpepi** [comment] 2023-03-24 21:31
Jaron Droder also did QA testing.

**Comment by pixelzoom** [comment] 2023-03-24 22:59
Jaron Droder has been added for https://github.com/phetsims/qa/issues/921.

**Comment by pixelzoom** [comment] 2023-03-24 22:59
Jaron Droder has been added for https://github.com/phetsims/qa/issues/921.

**Comment by pixelzoom** [comment] 2023-03-28 18:26
The 1.0 release branch has been created.  So any additional credits changes will need to be pushed to master, then cherry-picked to calculus-grapher 1.0 branch.

**Comment by veillette** [comment] 2023-04-13 19:26
For https://github.com/phetsims/calculus-grapher/issues/202, QA should confirm that the credits are up to date.

**Comment by veillette** [comment] 2023-04-17 16:57
In https://github.com/phetsims/qa/issues/933, QA confirmed that the QA credits are up to date.

**Comment by veillette** [comment] 2023-04-17 19:46
The simulation has been published. Closing

**Comment by phet-dev** [comment] 2023-05-04 22:32
Reopening because there is a TODO marked for this issue.

**Closed** 2023-05-05 00:09 UTC
